### ISSUE TITLE
Example on Readme has incorrect import name

### ISSUE THREAD

**Issue by benjolitz** [ashleysommer/sanicpluginsframework#10]
Minor typo in Readme example. Apparently it is `from spf import SanicPluginsFramework` (plural) not `from spf import SanicPluginFramework` as illustrated in the readme.

**Comment by ashleysommer** [comment]
Thank you for pointing this out.
Yes, you are right. This was a naming change I made very early on in the project, but it seems I never updated the example in the Readme.

**Comment by ashleysommer** [comment]
Fixed with https://github.com/ashleysommer/sanicpluginsframework/commit/3e1ac61014ab3c690821e690517e04fdee9da122
