### ISSUE TITLE
Websocket routes

### ISSUE THREAD

**Issue by daniel-skog** [ashleysommer/sanicpluginsframework#3]
Hello!

Thank you for a really nice framework! Really enjoying the context sharing features. One question:
is it possible to use websocket routes with SPF plugins so that context can be shared?

**Comment by ashleysommer** [comment]
Hi,
Thank you for the positive feedback.
Yes, websocket routes are a feature that I would like to have in spf.
I don't have a lot of time right now (new baby) to work on that feature, but Im happy to take pull requests if someone else would like to add websocket routes support.

**Comment by ashleysommer** [comment]
@daniel-skog 
Websocket routes are implemented in the latest release (static routes too!).
https://github.com/ashleysommer/sanicpluginsframework/releases/tag/0.6.1.dev20180616
