### ISSUE TITLE
setup.py doesn't install plugins, only spf

### ISSUE THREAD

**Issue by garyo** [ashleysommer/sanicpluginsframework#6]
Since SPF now comes with contextualize plugin, it would be good if setup.py installs it. Right now it only installs the 'spf' package.
However, it's probably best if the plugins package gets renamed to spf-plugins or put underneath spf, e.g. spf.plugins. I can do this, just let me know which way you prefer.

**Comment by ashleysommer** [comment]
Thank you for bringing this to my attention. I didn't think to check if setup.py installs the plugins, I just assumed it does.
Yes, If you could go ahead and create a PR to put it under spf.plugins that would be great, and I'll merge it asap.
